import {
  IconLoader,
  IconGithub,
  IconGoogle,
  IconApple,
  IconTwitter,
  IconX,
  IconCheckmark1,
  IconCheckmark2,
  IconCheckCircle2,
  IconCircleX,
  IconCirclePlus,
  IconCircleMinus,
  IconChevronLeft,
  IconChevronRight,
  IconChevronBottom,
  IconChevronTop,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowDown,
  IconArrowRotateClockwise,
  IconArrowRotateCounterClockwise,
  IconHome,
  IconUser,
  IconPeople,
  IconPeopleCircle,
  IconSettingsGear1,
  IconSettingsGear2,
  IconMagnifyingGlass,
  IconMagnifyingGlass2,
  IconPlusLarge,
  IconPlusSmall,
  IconMinusSmall,
  IconCircleDotsCenter1,
  IconBell,
  IconBellOff,
  IconEmail1,
  IconEmail2,
  IconLock,
  IconUnlocked,
  IconEyeOpen,
  IconEyeSlash,
  IconEyeSlash2,
  IconMoon,
  IconSun,
  IconSparkle,
  IconSparkle2,
  IconStar,
  IconHeart,
  IconHeart2,
  IconChainLink1,
  IconChainLink2,
  IconBrokenChainLink1,
  IconClipboard,
  IconClipboard2,
  IconClipboard2Sparkle,
  IconTrashCan,
  IconTrashCanSimple,
  IconEditBig,
  IconEditSmall1,
  IconEditSmall2,
  IconFolder1,
  IconFolder2,
  IconFiles,
  IconPageText,
  IconImageSparkle,
  IconImages1,
  IconImages2,
  IconVideo,
  IconAudio,
  IconCloud,
  IconCloudUpload,
  IconCloudDownload,
  IconCloudCheck,
  IconFileDownload,
  IconFolderUpload,
  IconSquareArrowTopRight,
  IconArrowRounded,
  IconRepeat,
  IconArrowsRepeat,
  IconPlay,
  IconPause,
  IconStop,
  IconSkip,
  IconBackward,
  IconStepForwards,
  IconStepBack,
  IconVolumeFull,
  IconVolumeOff,
  IconMute,
  IconMicrophone,
  IconMicrophoneOff,
  IconCamera1,
  IconCamera2,
  IconCameraOff,
  IconPhone,
  IconVideoOn,
  IconVideoOff,
  IconFilter1,
  IconFilter2,
  IconFilterAscending,
  IconFilterDescending,
  IconLayoutGrid1,
  IconLayoutGrid2,
  IconLayoutDashboard,
  IconSidebar,
  IconSidebarFloating,
  IconDashboardLow,
  IconDashboardMiddle,
  IconDashboardFast,
  IconChart1,
  IconChart2,
  IconChart3,
  IconChart4,
  IconChart5,
  IconChart6,
  IconChart7,
  IconChartWaterfall,
  IconPieChart1,
  IconPieChart2,
  IconCalendar1,
  IconCalendarCheck,
  IconClock,
  IconClockSnooze,
  IconWarningSign,
  IconCircleInfo,
  IconCircleQuestionmark,
  IconCircleDashed,
  IconCheckCircle2Dashed,
  IconZap,
  IconBolt,
  IconNoFlash,
  IconLightBulb,
  IconLightBulbSimple,
  IconLightbulbSparkle,
  IconRocket,
  IconCode,
  IconConsoleSimple,
  IconConsoleSparkle,
  IconConsoleSimple1,
  IconBug,
  IconBrackets1,
  IconBrackets2,
  IconCodeLines,
  IconCodeLarge,
  IconCodeMedium,
  IconMagicWand,
  IconMagicWand2,
  IconBrain,
  IconBrain1,
  IconBrain2,
  IconChip,
  IconChipSimple,
  IconServer,
  IconServer1,
  IconServer2,
  IconStorage,
  IconGlobe,
  IconGlobe2,
  IconTranslate,
  IconCurrencyDollar,
  IconCoin1,
  IconCoin2,
  IconWallet1,
  IconCreditCard1,
  IconCreditCard2,
  IconShoppingBag1,
  IconShoppingBag2,
  IconBag,
  IconTag,
  IconPercent,
  IconGift1,
  IconGift2,
  IconGiftBox,
  IconFire1,
  IconFire2,
  IconFire3,
  IconTrending1,
  IconTrending2,
  IconTrending3,
  IconTrending4,
  IconTrending5,
  IconTarget,
  IconTarget1,
  IconTarget2,
  IconTrophy,
  IconMedal,
  IconGoldMedal,
  IconSilverMedal,
  IconBronceMedal,
  IconCrown,
  IconBuildings,
  IconBuildingBlocks,
  IconToolbox,
  IconHammer,
  IconHammer2,
  IconBrush,
  IconPencil,
  IconPencil2,
  IconPencil3,
  IconEraser,
  IconH1,
  IconH2,
  IconH3,
  IconBold,
  IconItalic,
  IconUnderline,
  IconAlignmentLeft,
  IconAlignmentCenter,
  IconAlignmentRight,
  IconAlignmentJustify,
} from "@central-icons-react/round-outlined-radius-3-stroke-1.5";

export {
  IconLoader,
  IconGithub,
  IconGoogle,
  IconApple,
  IconTwitter,
  IconX,
  IconCheckmark1,
  IconCheckmark2,
  IconCheckCircle2,
  IconCircleX,
  IconCirclePlus,
  IconCircleMinus,
  IconChevronLeft,
  IconChevronRight,
  IconChevronBottom,
  IconChevronTop,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowDown,
  IconArrowRotateClockwise,
  IconArrowRotateCounterClockwise,
  IconHome,
  IconUser,
  IconPeople,
  IconPeopleCircle,
  IconSettingsGear1,
  IconSettingsGear2,
  IconMagnifyingGlass,
  IconMagnifyingGlass2,
  IconPlusLarge,
  IconPlusSmall,
  IconMinusSmall,
  IconCircleDotsCenter1,
  IconBell,
  IconBellOff,
  IconEmail1,
  IconEmail2,
  IconLock,
  IconUnlocked,
  IconEyeOpen,
  IconEyeSlash,
  IconEyeSlash2,
  IconMoon,
  IconSun,
  IconSparkle,
  IconSparkle2,
  IconStar,
  IconHeart,
  IconHeart2,
  IconChainLink1,
  IconChainLink2,
  IconBrokenChainLink1,
  IconClipboard,
  IconClipboard2,
  IconClipboard2Sparkle,
  IconTrashCan,
  IconTrashCanSimple,
  IconEditBig,
  IconEditSmall1,
  IconEditSmall2,
  IconFolder1,
  IconFolder2,
  IconFiles,
  IconPageText,
  IconImageSparkle,
  IconImages1,
  IconImages2,
  IconVideo,
  IconAudio,
  IconCloud,
  IconCloudUpload,
  IconCloudDownload,
  IconCloudCheck,
  IconFileDownload,
  IconFolderUpload,
  IconSquareArrowTopRight,
  IconArrowRounded,
  IconRepeat,
  IconArrowsRepeat,
  IconPlay,
  IconPause,
  IconStop,
  IconSkip,
  IconBackward,
  IconStepForwards,
  IconStepBack,
  IconVolumeFull,
  IconVolumeOff,
  IconMute,
  IconMicrophone,
  IconMicrophoneOff,
  IconCamera1,
  IconCamera2,
  IconCameraOff,
  IconPhone,
  IconVideoOn,
  IconVideoOff,
  IconFilter1,
  IconFilter2,
  IconFilterAscending,
  IconFilterDescending,
  IconLayoutGrid1,
  IconLayoutGrid2,
  IconLayoutDashboard,
  IconSidebar,
  IconSidebarFloating,
  IconDashboardLow,
  IconDashboardMiddle,
  IconDashboardFast,
  IconChart1,
  IconChart2,
  IconChart3,
  IconChart4,
  IconChart5,
  IconChart6,
  IconChart7,
  IconChartWaterfall,
  IconPieChart1,
  IconPieChart2,
  IconCalendar1,
  IconCalendarCheck,
  IconClock,
  IconClockSnooze,
  IconWarningSign,
  IconCircleInfo,
  IconCircleQuestionmark,
  IconCircleDashed,
  IconCheckCircle2Dashed,
  IconZap,
  IconBolt,
  IconNoFlash,
  IconLightBulb,
  IconLightBulbSimple,
  IconLightbulbSparkle,
  IconRocket,
  IconCode,
  IconConsoleSimple,
  IconConsoleSparkle,
  IconConsoleSimple1,
  IconBug,
  IconBrackets1,
  IconBrackets2,
  IconCodeLines,
  IconCodeLarge,
  IconCodeMedium,
  IconMagicWand,
  IconMagicWand2,
  IconBrain,
  IconBrain1,
  IconBrain2,
  IconChip,
  IconChipSimple,
  IconServer,
  IconServer1,
  IconServer2,
  IconStorage,
  IconGlobe,
  IconGlobe2,
  IconTranslate,
  IconCurrencyDollar,
  IconCoin1,
  IconCoin2,
  IconWallet1,
  IconCreditCard1,
  IconCreditCard2,
  IconShoppingBag1,
  IconShoppingBag2,
  IconBag,
  IconTag,
  IconPercent,
  IconGift1,
  IconGift2,
  IconGiftBox,
  IconFire1,
  IconFire2,
  IconFire3,
  IconTrending1,
  IconTrending2,
  IconTrending3,
  IconTrending4,
  IconTrending5,
  IconTarget,
  IconTarget1,
  IconTarget2,
  IconTrophy,
  IconMedal,
  IconGoldMedal,
  IconSilverMedal,
  IconBronceMedal,
  IconCrown,
  IconBuildings,
  IconBuildingBlocks,
  IconToolbox,
  IconHammer,
  IconHammer2,
  IconBrush,
  IconPencil,
  IconPencil2,
  IconPencil3,
  IconEraser,
  IconH1,
  IconH2,
  IconH3,
  IconBold,
  IconItalic,
  IconUnderline,
  IconAlignmentLeft,
  IconAlignmentCenter,
  IconAlignmentRight,
  IconAlignmentJustify,
};

export type { CentralIconBaseProps } from "@central-icons-react/round-outlined-radius-3-stroke-1.5";

import { type CentralIconBaseProps } from "@central-icons-react/round-outlined-radius-3-stroke-1.5";
import { cn } from "@onelens/ui/lib/utils";
import { type ComponentType, type FC, type SVGAttributes, type SVGProps } from "react";

export interface IconProps extends SVGAttributes<SVGSVGElement> {
  size?: "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | number;
}

const sizeMap = {
  xs: 12,
  sm: 14,
  md: 16,
  lg: 20,
  xl: 24,
  "2xl": 32,
} as const;

function getSizeValue(size: IconProps["size"]): string | number | undefined {
  if (size === undefined) return undefined;
  if (typeof size === "number") return size;
  return sizeMap[size];
}

export const createIcon = (
  IconComponent: ComponentType<CentralIconBaseProps>
) => {
  const IconWrapper: FC<IconProps> = ({ size, className, ...props }) => {
    const resolvedSize = getSizeValue(size);

    return (
      <span
        className={cn(
          "inline-flex shrink-0 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4",
          className
        )}
        aria-hidden={props["aria-hidden"] ?? true}
      >
        <IconComponent size={resolvedSize} {...props} />
      </span>
    );
  };

  const componentName =
    IconComponent.displayName || (IconComponent as { name?: string }).name || "Icon";
  IconWrapper.displayName = componentName;

  return IconWrapper;
};




const GitHub = (props: SVGProps<SVGSVGElement>) => (
  <svg {...props} viewBox="0 0 1024 1024" fill="none">
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M512 0C229.12 0 0 229.12 0 512c0 226.56 146.56 417.92 350.08 485.76 25.6 4.48 35.2-10.88 35.2-24.32 0-12.16-.64-52.48-.64-95.36-128.64 23.68-161.92-31.36-172.16-60.16-5.76-14.72-30.72-60.16-52.48-72.32-17.92-9.6-43.52-33.28-.64-33.92 40.32-.64 69.12 37.12 78.72 52.48 46.08 77.44 119.68 55.68 149.12 42.24 4.48-33.28 17.92-55.68 32.64-68.48-113.92-12.8-232.96-56.96-232.96-252.8 0-55.68 19.84-101.76 52.48-137.6-5.12-12.8-23.04-65.28 5.12-135.68 0 0 42.88-13.44 140.8 52.48 40.96-11.52 84.48-17.28 128-17.28s87.04 5.76 128 17.28c97.92-66.56 140.8-52.48 140.8-52.48 28.16 70.4 10.24 122.88 5.12 135.68 32.64 35.84 52.48 81.28 52.48 137.6 0 196.48-119.68 240-233.6 252.8 18.56 16 34.56 46.72 34.56 94.72 0 68.48-.64 123.52-.64 140.8 0 13.44 9.6 29.44 35.2 24.32C877.44 929.92 1024 737.92 1024 512 1024 229.12 794.88 0 512 0"
      clipRule="evenodd"
    />
  </svg>
);

export { GitHub };
