/**
 * OneLens — Inbox Data Model
 *
 * This is the single shape returned from the database for the /inbox route.
 * All four sections (your queue, merge-ready, needs changes, merged) are
 * fetched in one query and typed with a discriminated union on `status`.
 *
 * The `ai` block is generated once when the PR is opened (or re-generated
 * when the head SHA changes) and stored on the pull_requests row — it is
 * NOT re-computed on every page load.
 */

// ─── Primitives ──────────────────────────────────────────────────────────────

export type RiskLevel = "low" | "medium" | "high";

export type CiState = "passed" | "failed" | "flaky" | "pending" | "skipped";

export type DeployState = "success" | "failed" | "in_progress" | "cancelled";

export type PRStatus =
	| "open" // in YOUR QUEUE — reviewer has not acted yet
	| "merge_ready" // all checks green, approved, no unresolved comments
	| "changes_requested"
	| "merged"
	| "closed";

// ─── Sub-shapes ──────────────────────────────────────────────────────────────

export interface Author {
	/** Full avatar URL from GitHub */
	avatarUrl: string | null;
	/** GitHub login, e.g. "alexkim" */
	githubLogin: string;
	/** Internal user ID (null if external / open-source contributor) */
	id: string | null;
	/** 2-letter initials fallback when no avatar is available */
	initials: string;
	/** Display name, e.g. "Alex Kim" */
	name: string;
}

export interface CiSummary {
	/** True if any failing checks have a historical flakiness rate > 5% */
	hasFlaky: boolean;
	/** How many are currently passing */
	passingChecks: number;
	/**
	 * Human-readable plain-English reason — already interpreted by OneLens.
	 * NOT the raw CI output. E.g. "2 tests flaky (14% historical failure rate)"
	 * rather than "exit code 1: AssertionError in test_webhook_retry.py".
	 */
	reason: string;
	state: CiState;
	/** Total number of checks */
	totalChecks: number;
}

export interface DeploySummary {
	/** Vercel deployment URL for the production deploy */
	deployUrl: string | null;
	/** Human-readable deploy duration, e.g. "2m 14s" */
	duration: string;
	state: DeployState;
}

export interface LinearTicket {
	id: string; // e.g. "ENG-412"
	title: string;
	url: string;
}

/**
 * The AI block — generated by Claude Haiku once per PR (re-generated on
 * new commits). Stored on the pull_requests row in Postgres.
 *
 * This is the single source of truth for the AI brief shown:
 *   — as a one-liner in the inbox row  (use `inboxSummary`)
 *   — as the full brief at the top of /pr/[id]  (use `description` + `riskReason` + `testInstructions`)
 */
export interface AiBlock {
	/**
	 * 2–4 sentence description for the top of the PR review page.
	 * Covers: what changed, why (from the Linear ticket), and how it was implemented.
	 */
	description: string;

	/** ISO timestamp of when this AI block was last generated */
	generatedAt: string;
	/**
	 * 8–12 word summary for the inbox row subtitle.
	 * Written as a plain statement of what changed, not a commit message.
	 * Examples:
	 *   "Adds exponential backoff to prevent duplicate Stripe charges"
	 *   "Rate-limits auth endpoints; no schema or data changes"
	 *   "Migrates 3 preference columns to a new JSON structure"
	 */
	inboxSummary: string;

	/** The computed risk level */
	riskLevel: RiskLevel;

	/**
	 * One sentence explaining the risk rating.
	 * Examples:
	 *   "Touches payment-critical retry path with no feature flag fallback."
	 *   "Additive middleware change; existing auth flow is unchanged."
	 *   "Schema migration is reversible but affects all user preference reads."
	 */
	riskReason: string;

	/**
	 * GitHub login of the suggested reviewer, computed by blame scoring.
	 * Null if the author is the only person who has touched these files.
	 */
	suggestedReviewer: string | null;

	/**
	 * Plain-English instructions for how to manually test this PR.
	 * Derived from the diff + Linear ticket acceptance criteria.
	 */
	testInstructions: string;
}

// ─── The PR union — discriminated on `status` ────────────────────────────────

export interface PRBase {
	/** The AI-generated block. Null only if the pipeline hasn't run yet (<30s after open) */
	ai: AiBlock | null;
	author: Author;
	ci: CiSummary;
	/** Human-readable PR number, e.g. "PR-142" */
	displayId: string;
	/** Internal DB UUID */
	id: string;
	/** The linked Linear ticket, if branch name matches /[A-Z]+-\d+/i */
	linearTicket: LinearTicket | null;
	/** ISO timestamp — used for sorting */
	openedAt: string;
	/** Relative timestamp for display, e.g. "3h", "1d" */
	openedRelative: string;
	/** e.g. "payments/api" — owner + repo slug */
	repo: string;
	/** Current PR status — drives which inbox section this row appears in */
	status: PRStatus;
	/** PR title (from GitHub, editable) */
	title: string;
}

export interface OpenPR extends PRBase {
	status: "open";
}

export interface MergeReadyPR extends PRBase {
	/** Number of approved reviews */
	approvals: number;
	status: "merge_ready";
}

export interface ChangesRequestedPR extends PRBase {
	/**
	 * The single most important blocking reason, surfaced by OneLens.
	 * Derived from review comments — not raw comment text.
	 * E.g. "Missing fallback for disabled flags (flagged by @rn)"
	 */
	blockingReason: string;
	status: "changes_requested";
	/** Number of unresolved review comments */
	unresolvedComments: number;
}

export interface MergedPR extends PRBase {
	deploy: DeploySummary | null;
	/** ISO timestamp */
	mergedAt: string;
	/** Relative display string, e.g. "Mar 28" */
	mergedAtRelative: string;
	status: "merged";
}

export interface ClosedPR extends PRBase {
	closedAt: string;
	status: "closed";
}

export type PR =
	| OpenPR
	| MergeReadyPR
	| ChangesRequestedPR
	| MergedPR
	| ClosedPR;

// ─── The inbox response — one DB call, four sections ─────────────────────────

/**
 * Shape returned by GET /api/inbox (or the oRPC `inbox.get` procedure).
 *
 * Sections are pre-split server-side so the UI just renders four lists.
 * Each section is sorted by `openedAt` descending (most recent first).
 */
export interface InboxData {
	/** Recently merged PRs — last 14 days, capped at 10 rows */
	merged: MergedPR[];
	/** PRs ready to be merged — all checks green, fully approved */
	mergeReady: MergeReadyPR[];
	/** PRs the current user authored that have been sent back */
	needsChanges: ChangesRequestedPR[];
	/** PRs assigned to the current user that need their review */
	yourQueue: OpenPR[];
}

// ─── Fixture data ─────────────────────────────────────────────────────────────

export const INBOX_FIXTURE: InboxData = {
	yourQueue: [
		{
			id: "pr_9f3a1c",
			displayId: "PR-142",
			title: "Refactor Stripe webhook retry logic to prevent duplicate charges",
			repo: "payments/api",
			status: "open",
			author: {
				id: "usr_ak1",
				name: "Alex Kim",
				githubLogin: "alexkim",
				initials: "AK",
				avatarUrl: null,
			},
			openedRelative: "3h",
			openedAt: "2026-03-31T09:00:00Z",
			linearTicket: {
				id: "ENG-412",
				title: "Prevent duplicate charges on webhook retry",
				url: "https://linear.app/eng/issue/ENG-412",
			},
			ai: {
				inboxSummary:
					"Adds exponential backoff to prevent duplicate Stripe charges on retry",
				description:
					"Replaces the existing linear retry loop in the Stripe webhook handler with exponential backoff and idempotency key enforcement. This change addresses ENG-412, where network blips were causing the retry loop to fire multiple times within the deduplication window, resulting in duplicate charges. The core change is in `webhook.service.ts`; the test suite adds 6 new cases covering the retry boundary conditions.",
				riskLevel: "high",
				riskReason:
					"Touches the payment-critical retry path with no feature flag; a regression here causes real duplicate charges.",
				testInstructions:
					"Trigger a webhook with a simulated 500 response and confirm only one charge appears in Stripe's dashboard after the retry window. Run `pnpm test payments/api` to verify the 6 new retry boundary tests pass.",
				suggestedReviewer: "sarahchen",
				generatedAt: "2026-03-31T09:01:14Z",
			},
			ci: {
				state: "failed",
				reason:
					"1 test failing: `webhook_retry_dedup` (non-flaky — 0% historical failure rate)",
				totalChecks: 8,
				passingChecks: 7,
				hasFlaky: false,
			},
		},
		{
			id: "pr_2b7e9d",
			displayId: "PR-139",
			title: "Add rate limiting middleware for auth endpoints",
			repo: "api/auth",
			status: "open",
			author: {
				id: "usr_mt1",
				name: "Maya Torres",
				githubLogin: "mayatorres",
				initials: "MT",
				avatarUrl: null,
			},
			openedRelative: "5h",
			openedAt: "2026-03-31T07:00:00Z",
			linearTicket: {
				id: "ENG-408",
				title: "Rate limit /auth/* to prevent brute-force attacks",
				url: "https://linear.app/eng/issue/ENG-408",
			},
			ai: {
				inboxSummary:
					"Rate-limits auth endpoints at 10 req/min; no schema or data changes",
				description:
					"Inserts a Redis-backed rate limiting middleware into the auth router, capping requests to 10 per minute per IP. Implements ENG-408. The change is purely additive — no existing auth logic is modified, and the middleware short-circuits before any database reads, so there is no performance impact on non-throttled requests. The Redis TTL key format is `rl:auth:{ip}:{window_start}`.",
				riskLevel: "medium",
				riskReason:
					"Additive change, but an off-by-one in the window calculation could lock out legitimate users.",
				testInstructions:
					"Hit `/auth/login` 11 times in under 60 seconds from the same IP and confirm the 11th request returns 429. Verify that waiting 60s resets the counter. Check that existing auth integration tests still pass.",
				suggestedReviewer: "jsmith",
				generatedAt: "2026-03-31T07:01:08Z",
			},
			ci: {
				state: "passed",
				reason: "All 12 checks green",
				totalChecks: 12,
				passingChecks: 12,
				hasFlaky: false,
			},
		},
		{
			id: "pr_5c2f8b",
			displayId: "PR-136",
			title: "Migrate user preferences to new JSON schema",
			repo: "core/db",
			status: "open",
			author: {
				id: "usr_rn1",
				name: "Raj Nair",
				githubLogin: "rajnair",
				initials: "RN",
				avatarUrl: null,
			},
			openedRelative: "8h",
			openedAt: "2026-03-31T04:00:00Z",
			linearTicket: {
				id: "ENG-401",
				title: "Migrate preferences columns to JSONB",
				url: "https://linear.app/eng/issue/ENG-401",
			},
			ai: {
				inboxSummary:
					"Migrates 3 preference columns to JSONB; migration is reversible",
				description:
					"Consolidates `theme`, `notifications_enabled`, and `locale` columns into a single `preferences` JSONB column. Implements ENG-401. Includes both the up and down migration, and a backfill script that runs as a background job to avoid locking the table. The ORM layer is updated to read from the new column with a fallback to the old columns during the transition window.",
				riskLevel: "medium",
				riskReason:
					"Schema migration touches every user row; rollback is possible but requires re-running the backfill in reverse.",
				testInstructions:
					"Run `pnpm migrate:up` in a staging environment and verify user preference reads return correct values. Run the backfill script on a copy of production data and confirm zero null preferences after completion.",
				suggestedReviewer: "sarahchen",
				generatedAt: "2026-03-31T04:01:22Z",
			},
			ci: {
				state: "flaky",
				reason:
					"2 tests failing intermittently (14% historical failure rate — likely flaky)",
				totalChecks: 10,
				passingChecks: 8,
				hasFlaky: true,
			},
		},
	],

	mergeReady: [
		{
			id: "pr_7d4a2e",
			displayId: "PR-131",
			title: "Update onboarding copy and CTA button hierarchy",
			repo: "web/onboarding",
			status: "merge_ready",
			author: {
				id: "usr_lc1",
				name: "Lena Chen",
				githubLogin: "lenachen",
				initials: "LC",
				avatarUrl: null,
			},
			openedRelative: "1d",
			openedAt: "2026-03-30T12:00:00Z",
			linearTicket: {
				id: "ENG-395",
				title: "Onboarding copy refresh Q2",
				url: "https://linear.app/eng/issue/ENG-395",
			},
			approvals: 2,
			ai: {
				inboxSummary: "Copy-only change to onboarding flow; zero logic touched",
				description:
					"Updates headline copy, subheading, and primary CTA label on the 3-step onboarding flow per the Q2 copy refresh in ENG-395. No component logic, routing, or analytics events were modified. The change is isolated to two files: `OnboardingStep1.tsx` and `OnboardingStep3.tsx`.",
				riskLevel: "low",
				riskReason: "Pure copy change with no logic or data dependencies.",
				testInstructions:
					"Load `/onboarding` in staging and verify the new headline and CTA text appear on steps 1 and 3. No functional testing required.",
				suggestedReviewer: "mayatorres",
				generatedAt: "2026-03-30T12:01:05Z",
			},
			ci: {
				state: "passed",
				reason: "Stable across last 25 runs",
				totalChecks: 6,
				passingChecks: 6,
				hasFlaky: false,
			},
		},
		{
			id: "pr_1e8c3f",
			displayId: "PR-128",
			title: "Fix pagination offset bug in dashboard list view",
			repo: "web/dashboard",
			status: "merge_ready",
			author: {
				id: "usr_ap1",
				name: "Arjun Patel",
				githubLogin: "arjunpatel",
				initials: "AP",
				avatarUrl: null,
			},
			openedRelative: "22h",
			openedAt: "2026-03-30T14:00:00Z",
			linearTicket: {
				id: "ENG-398",
				title: "Pagination off-by-one on dashboard list",
				url: "https://linear.app/eng/issue/ENG-398",
			},
			approvals: 1,
			ai: {
				inboxSummary:
					"Off-by-one fix in dashboard pagination; one-line change, no regressions",
				description:
					"Fixes an off-by-one error in the `usePaginatedList` hook where the offset calculation was using `page * limit` instead of `(page - 1) * limit`, causing page 2 to skip the first item on page 1. Covers ENG-398. The fix is a single character change; a regression test is added to pin the correct offset behaviour.",
				riskLevel: "low",
				riskReason:
					"Single-line fix in a utility hook with a new regression test.",
				testInstructions:
					"Navigate to the dashboard, go to page 2 of any list, and verify the first item on page 2 is different from the last item on page 1. Run `pnpm test web/dashboard`.",
				suggestedReviewer: "lenachen",
				generatedAt: "2026-03-30T14:01:17Z",
			},
			ci: {
				state: "passed",
				reason: "No regressions detected across 18 checks",
				totalChecks: 18,
				passingChecks: 18,
				hasFlaky: false,
			},
		},
	],

	needsChanges: [
		{
			id: "pr_3a6d1c",
			displayId: "PR-125",
			title: "Replace legacy feature flag system with new SDK",
			repo: "core/config",
			status: "changes_requested",
			author: {
				id: "usr_rn1",
				name: "Raj Nair",
				githubLogin: "rajnair",
				initials: "RN",
				avatarUrl: null,
			},
			openedRelative: "2d",
			openedAt: "2026-03-29T12:00:00Z",
			linearTicket: {
				id: "ENG-387",
				title: "Migrate feature flags to LaunchDarkly SDK v3",
				url: "https://linear.app/eng/issue/ENG-387",
			},
			unresolvedComments: 5,
			blockingReason:
				"Missing fallback value for disabled flags — could throw on flag reads in production",
			ai: {
				inboxSummary:
					"Replaces internal flag system with LaunchDarkly SDK v3; missing disabled fallback",
				description:
					"Removes the homegrown `FeatureFlag` model and replaces all flag reads with the LaunchDarkly SDK v3 client. Addresses ENG-387. The migration covers 14 flag call sites across `core/config` and `web/app`. Review has identified a missing fallback: when a flag is disabled or the SDK is unavailable, the current implementation throws instead of returning the default value, which is a production risk.",
				riskLevel: "medium",
				riskReason:
					"Touches 14 flag call sites across two packages; the missing disabled fallback is a blocker.",
				testInstructions:
					"Add a default value parameter to `getFlag()` and verify that disabling a flag in the LaunchDarkly dashboard returns the default rather than throwing. Run the full flag integration test suite.",
				suggestedReviewer: "alexkim",
				generatedAt: "2026-03-29T12:01:33Z",
			},
			ci: {
				state: "passed",
				reason:
					"All checks passing — CI does not cover the missing fallback case",
				totalChecks: 9,
				passingChecks: 9,
				hasFlaky: false,
			},
		},
	],

	merged: [
		{
			id: "pr_6b2e7a",
			displayId: "PR-120",
			title: "Add CSV export to analytics page",
			repo: "web/analytics",
			status: "merged",
			author: {
				id: "usr_js1",
				name: "Jamie Sato",
				githubLogin: "jamiesato",
				initials: "JS",
				avatarUrl: null,
			},
			openedRelative: "3d",
			openedAt: "2026-03-28T10:00:00Z",
			mergedAt: "2026-03-28T18:30:00Z",
			mergedAtRelative: "Mar 28",
			linearTicket: {
				id: "ENG-380",
				title: "CSV export for analytics dashboard",
				url: "https://linear.app/eng/issue/ENG-380",
			},
			ai: {
				inboxSummary:
					"Adds CSV export button to analytics page; uses existing query layer",
				description:
					"Adds a CSV export action to the analytics dashboard that streams the current filtered dataset as a downloadable CSV. Implements ENG-380. Uses the existing `analyticsQuery` layer with no new database queries — the export reuses the same filters and date range as the current view.",
				riskLevel: "low",
				riskReason:
					"Additive feature using an existing query layer; no data mutations.",
				testInstructions:
					"Apply filters on the analytics page, click Export, and verify the downloaded CSV matches the filtered rows. Check that large datasets (>50k rows) stream without a timeout.",
				suggestedReviewer: null,
				generatedAt: "2026-03-28T10:01:02Z",
			},
			ci: {
				state: "passed",
				reason: "All checks green",
				totalChecks: 11,
				passingChecks: 11,
				hasFlaky: false,
			},
			deploy: {
				state: "success",
				duration: "2m 14s",
				deployUrl: "https://acme.vercel.app",
			},
		},
		{
			id: "pr_4c9f5b",
			displayId: "PR-118",
			title: "Upgrade React to 19.1 across all packages",
			repo: "web/core",
			status: "merged",
			author: {
				id: "usr_lc1",
				name: "Lena Chen",
				githubLogin: "lenachen",
				initials: "LC",
				avatarUrl: null,
			},
			openedRelative: "4d",
			openedAt: "2026-03-27T09:00:00Z",
			mergedAt: "2026-03-27T21:00:00Z",
			mergedAtRelative: "Mar 27",
			linearTicket: {
				id: "ENG-375",
				title: "React 19.1 upgrade",
				url: "https://linear.app/eng/issue/ENG-375",
			},
			ai: {
				inboxSummary:
					"Upgrades React to 19.1 across monorepo; all 8 packages updated",
				description:
					"Bumps React and React DOM to 19.1 across all 8 packages in the monorepo. Addresses ENG-375. No API breakages were identified — the upgrade is compatible with the current codebase. Peer dependency warnings from `react-pdf` and `react-table` were resolved by pinning to their latest compatible versions.",
				riskLevel: "medium",
				riskReason:
					"Major version bump touching all packages; peer dependency changes could surface runtime issues not caught by tests.",
				testInstructions:
					"Run the full E2E suite in staging. Specifically check the analytics charts, the data table, and any PDF preview components which use the updated peer dependencies.",
				suggestedReviewer: null,
				generatedAt: "2026-03-27T09:01:44Z",
			},
			ci: {
				state: "passed",
				reason: "All checks green after peer dependency pin",
				totalChecks: 24,
				passingChecks: 24,
				hasFlaky: false,
			},
			deploy: {
				state: "success",
				duration: "3m 02s",
				deployUrl: "https://acme.vercel.app",
			},
		},
	],
};
